platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods'

target 'dChat' do
  # Pods for dChat
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
  pod 'RNReanimated', :podspec => '../node_modules/react-native-reanimated/RNReanimated.podspec'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  use_unimodules!

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNSha256', :path => '../node_modules/react-native-sha256'

  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

end
